[colors.primary]
foreground = "#f0f0f0"
background = "#0d0221"

[colors.normal]
black = "#1a1a2e"
red = "#f97e72"
green = "#00ffff"
yellow = "#ffff00"
blue = "#2d72d9"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#f0f0f0"

[colors.bright]
black = "#57576e"
red = "#ff9a8f"
green = "#80ffff"
yellow = "#ffff80"
blue = "#5a9eff"
magenta = "#ff80ff"
cyan = "#80ffff"
white = "#ffffff"
